version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
only_commits:
  message: /#build/
build:
  verbosity: minimal
after_build:
- cmd: 7z a UnityLauncherPro.zip %APPVEYOR_BUILD_FOLDER%\UnityLauncherPro\bin\Release\*.exe %APPVEYOR_BUILD_FOLDER%\UnityLauncherPro\bin\Release\*.exe.config
artifacts:
- path: UnityLauncherPro.zip
  name: deploy
deploy:
- provider: GitHub
  auth_token:
    secure: kmYSrl7Mx/PFDGcyC5gS/vpW2UJCVguEXZsQ0LtkfwmSzx+3noZOyPrbZQ8uWX2B
  artifact: deploy
